microserviceName: "identity"

image:
  repository: playeconomyacr.azurecr.io/play.identity
  tag: 1.0.10

envVariables:
  IdentitySettings__PathBase: /identity-svc
  IdentitySettings__CertificateCerFilePath: "/certificates/certificate.crt"
  IdentitySettings__CertificateKeyFilePath: "/certificates/certificate.key"
  IdentityServerSettings__Clients__0__RedirectUris__0: https://playeconomy-dns-service.eastus.cloudapp.azure.com/authentication/login-callback
  IdentityServerSettings__Clients__0__PostLogoutRedirectUris__0: https://playeconomy-dns-service.eastus.cloudapp.azure.com/authentication/logout-callback

resources:
  limits:
    memory: "256Mi"
    cpu: "300m"

container:
  port: 5002
  volumeMounts:
    - name: certificate-volume
      mountPath: /certificates 

volumes:
  - name: certificate-volume
    secret: 
      secretName: signing-cert
      items:
        - key: tls.key
          path: certificate.key
        - key: tls.crt
          path: certificate.crt

certificate: 
  secretName: signing-cert
  hostname: playeconomy-dns-service.eastus.cloudapp.azure.com

identityClientId: ea95a1e2-1a3d-46f2-8747-59fc56c45eb4